#ifndef _VOYAGER_CONFIG_H
#define _VOYAGER_CONFIG_H

#define DEFAULT_SCREEN_WIDTH 1024
#define DEFAULT_SCREEN_HEIGHT 768

#define PLAYER_SHIP_SPEED 6
#define PICKUP_SPEED 4

#define THRUSTER_SPEED 1
#define IMPULSE_SPEED 8
#define WARP_SPEED 90

#endif
